### ISSUE TITLE
ButterKnife

### ISSUE THREAD

**Issue by akoua** [ironSource/OneAdapter#10]
I thanks for this library, so I want to use ButterKnife to bind my view. I can not this.

**Comment by idanatz** [comment]
Hi akoua,
I have added support for ButterKnife and added an example of how to use it in the sample project.
Will be released in the next version in a few days.

**Comment by idanatz** [comment]
version v1.4.0 is out with ButterKnife support.
Please check the CHANGELOG and the README.
An example activity can be found in the sample project.
