### ISSUE TITLE
Stop swipe on left or on right

### ISSUE THREAD

**Issue by elghamry** [ironSource/OneAdapter#11]
i tried to stop the swipe on left or right and it couldn't be done 
thanks for amazing library

**Comment by idanatz** [comment]
Hi, thanks for the kind words
What do you mean by stop the swipe?
Once the user swipe has passed a certain threshold it cannot be stopped as the RecyclerView has registered it as a swipe intent.
What exactly are you trying to achieve?

**Comment by elghamry** [comment]
Your are welcome 
i mean that when you use swipe functionality in the adapter 
by default swipe left and right work 
i wanna make one of them off

**Comment by idanatz** [comment]
look at the SwipeEventHook class:
SwipeEventHook<T>(supportedSwipeDirections: SwipeDirection = SwipeDirection.values())

you can pass the direction of the supported swipe you wish, for example:
for right swipe: SwipeEventHook<YourModel>(SwipeDirection.Right)
for left swipe: SwipeEventHook<YourModel>(SwipeDirection.Left)

if none is specified then both Right and Left are supported.

Maybe in the next version, i will add a function to specify the supported direction to make this more clear, so keep an eye for a future version.

**Comment by elghamry** [comment]
okay i got the idea ... iam waiting for the amazing coming version :D 
thanks for your efforts
