### ISSUE TITLE
Selection without long click

### ISSUE THREAD

**Issue by THEAccess** [ironSource/OneAdapter#12]
First of all thank you for this great library which makes working with RecyclerView much easier.

OneAdapter supports selection with a long click. 
Unfortunately i have not yet found a way to enable selection with just a normal (short) click.
My first approach was to clone the project and implement it myself. Unfortunately the project is very complex and i couln't get it done.

**Is there any way to enable/implement selection with short clicks?** And is there a way to set a default selection?

Any help is appreciated.

**Comment by idanatz** [comment]
Hi, thanks for the kind words!
I will dig into it and try to add an option for selection with a short click in a future version.

With a quick search, I found 2 posts with potential solutions, give them a try:
https://stackoverflow.com/a/55154805/5516215
https://stackoverflow.com/a/55878940/5516215

**Comment by meruiden** [comment]
any updates on this

**Comment by idanatz** [comment]
will be added in v2.0.0 coming in the next few days 🥳

**Comment by idanatz** [comment]
v2.0.0 is out with this feature,  pay attention to the breaking changes.
