### ISSUE TITLE
oneadapter.update(model) not working

### ISSUE THREAD

**Issue by tfaki** [ironSource/OneAdapter#14]
not working to undo view

**Comment by idanatz** [comment]
I just checked the update capabilities on the sample project and it works fine.
Please add more information about your problem or this issue will be closed.

**Comment by tfaki** [comment]
maybe I did wrong, my code is like this ;

private inner class PlaceItemSwipeEvent : SwipeEventHook<PlaceModel>() {
        override fun provideHookConfig(): SwipeEventHookConfig = object : SwipeEventHookConfig() {
            override fun withSwipeDirection() = listOf(SwipeDirection.Left)
        }

        override fun onSwipe(canvas: Canvas, xAxisOffset: Float, viewBinder: ViewBinder) {
          
            when {
                xAxisOffset < 0 -> paintSwipeLeft(canvas, xAxisOffset, viewBinder.rootView)
            }
        }

        override fun onSwipeComplete(model: PlaceModel, direction: SwipeDirection, viewBinder: ViewBinder) {

val alert = AlertDialog.Builder(this)
 
        alert.setTitle("title")
        alert.setCancelable(false);
        alert.setPositiveButton("Yes") { dialogInterface: DialogInterface, i: Int ->
            viewModel.deletePlace(model.placeId)
        alert.setNegativeButton("No") {dialogInterface: DialogInterface, i: Int ->
            oneAdapter.update(model)
        alert.show()

    }
}

**Comment by TalhaFaki** [comment]
maybe I did wrong, my code is like this ;

`private inner class PlaceItemSwipeEvent : SwipeEventHook() {
override fun provideHookConfig(): SwipeEventHookConfig = object : SwipeEventHookConfig() {
override fun withSwipeDirection() = listOf(SwipeDirection.Left)
}

    override fun onSwipe(canvas: Canvas, xAxisOffset: Float, viewBinder: ViewBinder) {
      
        when {
            xAxisOffset < 0 -> paintSwipeLeft(canvas, xAxisOffset, viewBinder.rootView)
        }
    }

    override fun onSwipeComplete(model: PlaceModel, direction: SwipeDirection, viewBinder: ViewBinder) {
val alert = AlertDialog.Builder(this)

    alert.setTitle("title")
    alert.setCancelable(false);
    alert.setPositiveButton("Yes") { dialogInterface: DialogInterface, i: Int ->
        viewModel.deletePlace(model.placeId)
    alert.setNegativeButton("No") {dialogInterface: DialogInterface, i: Int ->
        oneAdapter.update(model)
    alert.show()

}
}`

**Comment by idanatz** [comment]
This code is fully working with the sample project using SwipeEventHookActivity:

```
   inner class MessageSwipeHook : SwipeEventHook<MessageModel>() {
        override fun provideHookConfig(): SwipeEventHookConfig = object : SwipeEventHookConfig() {
            override fun withSwipeDirection() = listOf(SwipeDirection.Left)
        }

        override fun onSwipe(canvas: Canvas, xAxisOffset: Float, viewBinder: ViewBinder) {
            when {
                xAxisOffset < 0 -> paintSwipeLeft(canvas, xAxisOffset, viewBinder.rootView)
            }
        }

        override fun onSwipeComplete(model: MessageModel, direction: SwipeDirection, viewBinder: ViewBinder) {
            when (direction) {
                SwipeDirection.Left -> oneAdapter.remove(model)
                SwipeDirection.Right -> {
                    val alert = AlertDialog.Builder(this@SwipeEventHookActivity)
                    alert.setTitle("title")
                    alert.setCancelable(false)
                    alert.setPositiveButton("Yes") { dialogInterface: DialogInterface, i: Int ->
                        oneAdapter.remove(model)
                    }
                    alert.setNegativeButton("No") { dialogInterface: DialogInterface, i: Int ->
                        oneAdapter.update(model)
                    }
                    alert.show()
                }
            }
        }
    }
```

Just for reference, here is a GIF:
![gif](https://user-images.githubusercontent.com/40384226/71036331-261b0400-2126-11ea-886b-fab7499fd4fd.gif)

**Comment by tfaki** [comment]
Thanks for your attention, I will do better
