### ISSUE TITLE
Get item position from item module

### ISSUE THREAD

**Issue by meruiden** [ironSource/OneAdapter#17]
its not possible to make a layout where you have a list where every 1 item it has a darker background

- light background
- darker background
- light background
- darker background

It would be nice if I could get the item position from the ItemModule so that it would simple be:

```kotlin
val darkBackground = position % 2 == 1
```

from the onBind function

**Comment by idanatz** [comment]
Will add this data in the next version of the library

**Comment by idanatz** [comment]
Version 1.5.0 is out with this ability.
Please notice that there are breaking changes in the modules API due to this request.
The sample project is updated as well for reference.
