### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by meruiden** [ironSource/OneAdapter#19]
The readme docs for adding event hooks show the following example code:

```kotlin
val oneAdapter = OneAdapter(recyclerView)
    .attachItemModule(MessageModule()).addEventHook(MessageClickEvent())
    ...
```

there is a parenthese misplaced. 

Correct:

```kotlin
val oneAdapter = OneAdapter(recyclerView)
    .attachItemModule(MessageModule().addEventHook(MessageClickEvent()))
    ...
```

**Comment by meruiden** [comment]
And the ClickEventHook still returns the old model rather then the new Item model containing the metadata

**Comment by idanatz** [comment]
Thanks, you are correct.
Regarding the event hook, will be wrapped with Item<> in the next version 👍🏼
