### ISSUE TITLE
nested recyclerview

### ISSUE THREAD

**Issue by rakaadinugroho** [ironSource/OneAdapter#2]
how to create nested recyclerview to handling layoutManager orientation?

**Comment by idanatz** [comment]
same as you will create a nested recycle view with a regular adapter.
one of you ItemModule will hold a recycler view in its layout file and when the onBind gets called just populate that recycler view with different adapter and data.

for nested recycler view with regular adapter check this:
https://android.jlelse.eu/easily-adding-nested-recycler-view-in-android-a7e9f7f04047
