### ISSUE TITLE
Vertical Swipe Direction

### ISSUE THREAD

**Issue by Minification** [ironSource/OneAdapter#24]
Hi,

since RecyclerViews can be in horizontal mode (i.e. items are laid out horizontally), it would be great to have vertical swipe directions, i.e. ```SwipeDirection.UP``` and  ```SwipeDirection.DOWN```.

As a matter of fact, that would be really great for me to have right now...

Thanks for reading and keep up the great work!

**Comment by idanatz** [comment]
Hi, Thanks :)
Will be adding Up & Down directions in the next version later today
