### ISSUE TITLE
Does not work in Java

### ISSUE THREAD

**Issue by saiid2020** [ironSource/OneAdapter#27]
I only know Java, please support Java as well

**Comment by idanatz** [comment]
Did you check the sample project? it has a Java activity 
https://github.com/ironSource/OneAdapter/blob/develop/sample/app/src/main/java/com/idanatz/sample/examples/BasicJavaExampleActivity.java

**Comment by saiid2020** [comment]
Pagination does not work in Java 


static class Pagation extends PagingModule {

        public Pagation(OnLoadMore onLoadMore ) {
            config(builder->{
                builder.setLayoutResource(R.layout.item_progress);
                builder.setVisibleThreshold(10);
                return null;


            });
            onLoadMore(mo->{
                onLoadMore.onloadmore(mo);
                return null;



            });

        }



    }
        oneAdapter = new OneAdapter(recycler_product)
                .attachPagingModule(new Pagation(onLoadMore))
        .attachItemModule(new Productadaptermodel(onItemClickListener));

**Comment by idanatz** [comment]
I've updated the java sample with paging module and it working great
https://github.com/ironSource/OneAdapter/blob/develop/sample/app/src/main/java/com/idanatz/sample/examples/BasicJavaExampleActivity.java

**Comment by saiid2020** [comment]
I found a problem when I set the linearlayout after oneadapter, pagination does not work
