### ISSUE TITLE
Selection items selected other items

### ISSUE THREAD

**Issue by ghost** [ironSource/OneAdapter#31]
If i select an item in the recyclerview another gets highlight at the same time when scrolling. I tried the sample project and have the same result. Like this:

https://gph.is/g/EG7LJbl

**Comment by idanatz** [comment]
Thanks for the report!
Was introduced in the last version 😞
I've added a test to verify the bug and fixed it.
Will be available in the next version that will be released today/tomorrow

**Comment by idanatz** [comment]
v2.0.1 is out with the fix
