### ISSUE TITLE
Support for StateRestorationPolicy

### ISSUE THREAD

**Issue by meruiden** [ironSource/OneAdapter#32]
Hi,

Could you add support to get and set the StateRestorationPolicy? this is currently not accessible since the adapter is private.

**Edit:**
After peeking in OneAdapter.kt it can be done simply by adding this line:
```kotlin
    var stateRestorationPolicy: StateRestorationPolicy
        get() = internalAdapter.stateRestorationPolicy
        set(value) {
            internalAdapter.stateRestorationPolicy = value
        }
```

and it would be nice if the paginator could also implement some sort of state restoring so that after a state has been restored the pagination can go on where it left off

**Comment by idanatz** [comment]
Hi
I will expose the StateRestorationPolicy in the next version.
Also, I will try to integrate state restoration in the paginator as well.
Thanks

**Comment by meruiden** [comment]
Hi, any updates on this?

**Comment by idanatz** [comment]
Hi
Haven't got to the restoration request (busy schedule) but exposing the StateRestorationPolicy will be available in a couple of days in the next minor release.
Thanks

**Comment by idanatz** [comment]
v2.0.2 is out with your request
