### ISSUE TITLE
Preselected Items

### ISSUE THREAD

**Issue by Togka** [ironSource/OneAdapter#42]
Good day. Tell me if it is possible to somehow pre-select some elements of the list when forming the adapter elements?

**Comment by idanatz** [comment]
Hi,
Currently, there is no way to do that.
What you can do is start selection manually using:
`oneAdapter.modules.itemSelectionModule?.actions?.startSelection()`
 and then trigger a click programmatically on the root view of the element's view holder.
 I know it's not what you asked, but maybe you can achieve your goal with this direction.
