### ISSUE TITLE
Retry button

### ISSUE THREAD

**Issue by genaku** [ironSource/OneAdapter#45]
Is it possible to add retry button (and message TextView to show some error hint message) to paging module? (Like in Android Paging 3).

**Comment by idanatz** [comment]
Hey,
I can add a manual trigger to the paging module if it will help your use case.
Regarding the error or hint message, that's up to your implementation, the adapter does not trigger UI stuff by itself.
Based on your logic, when paging starts or failed you can show a Textview within the adapter using another ItemModule or any other way based on your needs.

Waiting for you feedback

**Comment by idanatz** [comment]
?
